
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 13 10:31:37 CST 2016
//----------------------------------------------------

package BackEnd.Analizador.Ecuaciones;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int potencia = 2;
  public static final int llavesf = 14;
  public static final int coma = 15;
  public static final int resta = 7;
  public static final int corchetei = 9;
  public static final int suma = 6;
  public static final int multiplicacion = 4;
  public static final int corchetef = 10;
  public static final int parentesisi = 11;
  public static final int EOF = 0;
  public static final int raiz = 3;
  public static final int parentesisf = 12;
  public static final int numero = 8;
  public static final int division = 5;
  public static final int error = 1;
  public static final int llavesi = 13;
}

