/* The following code was generated by JFlex 1.4.3 on 17/04/16 11:55 PM */

package BackEnd.Analizador.Compilador;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/04/16 11:55 PM from the specification file
 * <tt>AnalizadorLexico_compilador.Jflex</tt>
 */
public class Lexico_Request implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\17\1\0\2\67\22\0\1\67\1\0\1\15\1\20"+
    "\1\32\1\63\2\0\1\55\1\56\1\21\1\46\1\51\1\5\1\4"+
    "\1\16\1\2\1\14\10\2\1\0\1\50\1\0\1\52\2\0\1\6"+
    "\2\1\1\42\1\1\1\65\3\1\1\37\4\1\1\64\1\1\1\44"+
    "\1\1\1\45\2\1\1\40\1\62\4\1\1\53\1\0\1\54\1\0"+
    "\1\3\1\0\1\24\1\43\1\7\1\25\1\23\1\26\1\33\1\1"+
    "\1\13\2\1\1\30\1\11\1\27\1\10\1\12\1\35\1\22\1\31"+
    "\1\34\1\36\1\1\1\41\1\66\1\61\1\1\1\57\1\0\1\60"+
    "\123\0\1\1\37\0\1\47\uff0e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\4\2\1\1"+
    "\1\5\2\1\1\6\6\2\1\7\10\2\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\2\1\1\1\22\1\2\2\0\2\3\1\23\6\2"+
    "\1\24\3\0\1\25\2\0\1\26\1\0\5\2\1\27"+
    "\13\2\1\30\1\2\1\31\1\2\1\0\10\2\1\32"+
    "\4\0\7\2\1\33\10\2\1\34\2\2\1\0\1\2"+
    "\1\35\3\2\1\36\3\2\3\0\7\2\1\37\11\2"+
    "\1\0\1\2\1\40\1\2\1\41\3\2\3\0\1\2"+
    "\1\42\1\2\1\43\6\2\1\44\3\2\1\45\1\2"+
    "\1\0\1\46\4\2\3\0\3\2\1\47\1\2\1\50"+
    "\1\2\1\51\4\2\1\0\4\2\1\52\2\0\1\53"+
    "\5\2\1\54\1\2\1\55\1\0\1\56\1\2\1\57"+
    "\1\60\2\0\1\61\1\2\1\62\1\63\2\2\1\0"+
    "\1\2\2\0\1\64\2\2\1\0\1\2\2\0\1\65"+
    "\2\2\1\0\1\66\1\0\1\67\2\2\1\70\1\0"+
    "\1\2\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[251];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\70\0\u0310"+
    "\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\70\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\u0620\0\u0658\0\160\0\u0690\0\340\0\u06c8\0\u0700\0\u0738"+
    "\0\70\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888\0\160"+
    "\0\u08c0\0\u08f8\0\u0930\0\70\0\u0968\0\u09a0\0\70\0\u09d8"+
    "\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\160\0\u0b28\0\u0b60"+
    "\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20"+
    "\0\u0d58\0\160\0\u0d90\0\70\0\u0dc8\0\u0e00\0\u0e38\0\u0e70"+
    "\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\160\0\u0ff8"+
    "\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8"+
    "\0\u11f0\0\u1228\0\160\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340"+
    "\0\u1378\0\u13b0\0\u13e8\0\160\0\u1420\0\u1458\0\u1490\0\u14c8"+
    "\0\160\0\u1500\0\u1538\0\u1570\0\160\0\u15a8\0\u15e0\0\u1618"+
    "\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730\0\u1768\0\u17a0\0\u17d8"+
    "\0\u1810\0\u1848\0\160\0\u1880\0\u18b8\0\u18f0\0\u1928\0\u1960"+
    "\0\u1998\0\u19d0\0\u1a08\0\u1a40\0\u1a78\0\u1ab0\0\160\0\u1ae8"+
    "\0\160\0\u1b20\0\u1b58\0\u1b90\0\u1bc8\0\u1c00\0\u1c38\0\u1c70"+
    "\0\160\0\u1ca8\0\160\0\u1ce0\0\u1d18\0\u1d50\0\u1d88\0\u1dc0"+
    "\0\u1df8\0\160\0\u1e30\0\u1e68\0\u1ea0\0\160\0\u1ed8\0\u1f10"+
    "\0\160\0\u1f48\0\u1f80\0\u1fb8\0\u1ff0\0\u2028\0\u2060\0\u2098"+
    "\0\u20d0\0\u2108\0\u2140\0\160\0\u2178\0\160\0\u21b0\0\160"+
    "\0\u21e8\0\u2220\0\u2258\0\u2290\0\u22c8\0\u2300\0\u2338\0\u2370"+
    "\0\u23a8\0\70\0\u23e0\0\u2418\0\160\0\u2450\0\u2488\0\u24c0"+
    "\0\u24f8\0\u2530\0\160\0\u2568\0\160\0\u25a0\0\160\0\u25d8"+
    "\0\160\0\160\0\u2610\0\u2648\0\160\0\u2680\0\160\0\160"+
    "\0\u26b8\0\u26f0\0\u2728\0\u2760\0\u2798\0\u27d0\0\160\0\u2808"+
    "\0\u2840\0\u2878\0\u28b0\0\u28e8\0\u2920\0\70\0\u2958\0\u2990"+
    "\0\u29c8\0\160\0\u2a00\0\70\0\u2a38\0\u2a70\0\70\0\u2aa8"+
    "\0\u2ae0\0\160\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[251];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\2\1\7"+
    "\1\3\1\10\1\11\1\12\1\4\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\3\1\24"+
    "\1\3\1\25\1\26\1\27\1\30\1\31\1\3\1\32"+
    "\1\33\1\3\1\34\1\3\1\35\1\36\1\37\1\3"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\3\1\51\1\52\1\53\1\54\1\3\1\15"+
    "\71\0\3\3\1\0\1\55\1\56\6\3\5\0\10\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\1\55\1\57\1\55\1\60\1\55\1\56\5\55"+
    "\1\57\5\0\10\55\1\0\13\55\1\0\1\55\11\0"+
    "\2\55\1\0\3\55\2\0\3\55\1\0\1\55\1\56"+
    "\6\55\5\0\10\55\1\0\13\55\1\0\1\55\11\0"+
    "\2\55\1\0\3\55\2\0\3\55\1\0\1\55\1\56"+
    "\6\55\5\0\10\55\1\61\13\55\1\0\1\55\11\0"+
    "\2\55\1\0\3\55\2\0\3\3\1\0\1\55\1\56"+
    "\1\3\1\62\4\3\5\0\2\3\1\63\5\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\2\3\1\64"+
    "\5\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\1\65\1\3\1\66\5\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\2\3\1\67\3\3\5\0\3\3\1\70\4\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\1\0\7\71\1\72\1\71\1\73\3\71\1\74\5\71"+
    "\1\75\44\71\16\0\1\76\70\0\1\15\47\0\1\15"+
    "\20\0\1\77\1\100\47\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\3\1\101\6\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\2\3\1\102\3\3\5\0\10\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\3\3\1\103\2\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\1\3\1\104"+
    "\2\3\1\105\1\3\5\0\1\3\1\106\6\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\1\3\1\107\4\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\10\3\1\0\3\3\1\110\7\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\3\1\111\6\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\4\3\1\112\1\3\5\0\1\3\1\113"+
    "\1\114\5\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\10\3\1\0\3\3\1\115\7\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\5\3\1\116\2\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\7\3\1\117\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\1\120\7\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\6\3\5\0\10\3"+
    "\1\0\1\3\1\121\11\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\10\3\1\0\2\3\1\122\10\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\2\3\1\123\5\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\64\0\1\124"+
    "\5\0\3\3\1\0\1\55\1\56\6\3\5\0\10\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\2\3"+
    "\1\125\10\0\1\126\61\0\1\55\1\57\1\55\1\0"+
    "\1\55\1\56\5\55\1\57\5\0\10\55\1\0\13\55"+
    "\1\0\1\55\11\0\2\55\1\0\3\55\3\0\1\60"+
    "\11\0\1\60\54\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\3\3\1\127\1\3\1\130\1\131\1\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\5\3\1\132"+
    "\2\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\1\133\7\3\1\0\1\3\1\134\11\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\1\3\1\135\4\3\5\0\10\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\7\3\1\136\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\10\3\1\0"+
    "\1\137\12\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\1\0\15\71\1\74\67\71\1\74\4\71\1\140\55\71"+
    "\1\141\4\71\1\74\67\71\1\74\12\71\1\142\37\71"+
    "\17\76\1\2\50\76\20\100\1\0\1\143\46\100\1\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\10\3\1\0"+
    "\2\3\1\144\10\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\2\3\1\145\5\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\3\1\146\6\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\5\3\1\147\2\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\1\150\7\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\2\3\1\151\3\3"+
    "\5\0\10\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\1\152"+
    "\5\3\5\0\10\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\10\3\1\0\1\3\1\153\11\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\3\3\1\154\2\3\5\0\1\3\1\155"+
    "\6\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\6\3\1\156\1\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\2\3\1\157\3\3\5\0\10\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\1\3\1\160\6\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\4\3\1\161\1\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\10\3\1\0\3\3\1\162\7\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\3\1\163\6\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\5\3\1\164\2\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\1\165\5\3\5\0\10\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\6\3\5\0\10\3"+
    "\1\0\1\3\1\166\11\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\11\0\1\167\60\0\3\3\1\0\1\55"+
    "\1\56\4\3\1\170\1\3\5\0\10\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\7\3\1\171\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\1\3\1\172\4\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\10\3\1\0\1\3\1\173\11\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\1\174\5\3\5\0\10\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\1\3\1\175\6\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\3\3\1\176\2\3\5\0\3\3"+
    "\1\177\4\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\7\3\1\200\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\1\0\15\71\1\74\5\71\1\201"+
    "\61\71\1\74\7\71\1\202\55\71\1\203\1\71\1\74"+
    "\52\71\20\100\1\2\1\143\46\100\1\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\10\3\1\0\3\3\1\204"+
    "\7\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\4\3\1\205\1\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\6\3\1\206\1\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\3\3\1\207\4\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\1\3\1\210\6\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\10\3\1\0"+
    "\10\3\1\211\2\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\10\3\1\0\3\3\1\212\7\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\1\3\1\213\4\3\5\0\10\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\5\3\1\214\2\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\1\3\1\215"+
    "\6\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\2\3\1\216\5\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\217\7\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\1\220\5\3\5\0\10\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\2\3\1\221\5\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\2\3\1\222"+
    "\5\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\4\3\1\223"+
    "\1\3\5\0\10\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\224\7\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\12\0\1\225\57\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\10\3\1\0\1\226"+
    "\12\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\1\227\7\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\4\3\1\230\1\3"+
    "\5\0\10\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\2\3\1\231\5\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\4\3\1\232\1\3\5\0\10\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\10\3\1\0\3\3"+
    "\1\233\7\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\6\3\5\0\10\3"+
    "\1\0\6\3\1\234\4\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\1\0\15\71\1\74\6\71\1\235\56\71"+
    "\1\236\1\71\1\74\63\71\1\237\3\71\1\74\52\71"+
    "\1\0\3\3\1\0\1\55\1\56\6\3\5\0\1\3"+
    "\1\240\6\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\6\3\1\241\1\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\6\3\1\242\1\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\1\3\1\243\6\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\1\244\5\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\1\245\7\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\1\246\7\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\3\3\1\247\4\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\4\3\1\250\3\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\10\3\1\0"+
    "\13\3\1\0\1\251\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\10\3\1\0"+
    "\13\3\1\0\1\3\11\0\1\252\1\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\4\3\1\253\1\3"+
    "\5\0\10\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\1\254\7\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\1\255\7\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\1\3\1\256\4\3\5\0\10\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\2\3\1\257\5\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\13\0\1\260\56\0\3\3\1\0\1\55\1\56\1\3"+
    "\1\261\4\3\5\0\10\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\3\3\1\262\4\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\1\3\1\263\6\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\1\264\5\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\1\3\1\265"+
    "\4\3\5\0\10\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\1\0\15\71\1\74\4\71\1\266"+
    "\62\71\1\74\10\71\1\267\54\71\1\270\1\71\1\74"+
    "\52\71\1\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\7\3\1\271\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\4\3"+
    "\1\272\1\3\5\0\10\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\1\273\5\3\5\0\10\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\1\3\1\274\6\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\7\3\1\275"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\6\3\5\0\2\3"+
    "\1\276\5\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\1\3"+
    "\1\277\4\3\5\0\10\3\1\0\13\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\1\3\1\300\4\3\5\0\10\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\1\3\1\301\4\3\5\0\10\3"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\4\3\1\302\1\3"+
    "\5\0\10\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\10\3\1\0\5\3\1\303\5\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\1\3\1\304\6\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\14\0\1\305"+
    "\55\0\3\3\1\0\1\55\1\56\6\3\5\0\2\3"+
    "\1\306\5\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\10\3\1\0\1\3\1\307\11\3\1\0\1\3"+
    "\11\0\2\3\1\0\3\3\2\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\10\3\1\0\1\3\1\310\11\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\2\0\3\3"+
    "\1\0\1\55\1\56\6\3\5\0\1\311\7\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\1\0"+
    "\15\71\1\312\65\71\1\313\1\71\1\74\67\71\1\74"+
    "\11\71\1\314\40\71\1\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\10\3\1\0\1\3\1\315\11\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\3\3\1\316\4\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\4\3\1\317\1\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\2\3\1\320\5\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\5\3\1\321\2\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\10\3\1\0\5\3\1\322"+
    "\5\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\1\3\1\323\4\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\7\3\1\324\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\2\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\1\325\7\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\15\0\1\326\54\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\3\3\1\327\4\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\2\3\1\330"+
    "\5\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\1\3\1\331"+
    "\4\3\5\0\10\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\3\3\1\332\4\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\1\0\7\71\1\333"+
    "\5\71\1\74\67\71\1\74\6\71\1\334\43\71\1\0"+
    "\3\3\1\0\1\55\1\56\1\3\1\335\4\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\1\3\1\336"+
    "\4\3\5\0\10\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\6\3\1\337\1\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\1\3\1\340\4\3\5\0\10\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\7\3\1\341"+
    "\1\0\13\3\1\0\1\3\11\0\2\3\1\0\3\3"+
    "\2\0\3\3\1\0\1\55\1\56\6\3\5\0\10\3"+
    "\1\0\3\3\1\342\7\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\5\0\1\343\64\0\3\3\1\0\1\55"+
    "\1\56\6\3\5\0\1\344\7\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\1\0\15\71\1\74"+
    "\6\71\1\345\60\71\1\74\4\71\1\346\45\71\1\0"+
    "\3\3\1\0\1\55\1\56\6\3\5\0\5\3\1\347"+
    "\2\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\2\0\3\3\1\0\1\55\1\56\6\3\5\0"+
    "\10\3\1\0\3\3\1\350\7\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\2\3\1\351\5\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\10\0\1\352\61\0"+
    "\3\3\1\0\1\55\1\56\4\3\1\353\1\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\1\0\7\71\1\354\5\71\1\74\4\71\1\355"+
    "\62\71\1\356\52\71\1\0\3\3\1\0\1\55\1\56"+
    "\6\3\5\0\2\3\1\357\5\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\2\0\3\3\1\0"+
    "\1\55\1\56\6\3\5\0\1\360\7\3\1\0\13\3"+
    "\1\0\1\3\11\0\2\3\1\0\3\3\11\0\1\361"+
    "\60\0\3\3\1\0\1\55\1\56\1\3\1\362\4\3"+
    "\5\0\10\3\1\0\13\3\1\0\1\3\11\0\2\3"+
    "\1\0\3\3\1\0\13\71\1\363\1\71\1\74\67\71"+
    "\1\364\52\71\1\0\3\3\1\0\1\55\1\56\6\3"+
    "\5\0\1\365\7\3\1\0\13\3\1\0\1\3\11\0"+
    "\2\3\1\0\3\3\2\0\3\3\1\0\1\55\1\56"+
    "\4\3\1\366\1\3\5\0\10\3\1\0\13\3\1\0"+
    "\1\3\11\0\2\3\1\0\3\3\12\0\1\367\56\0"+
    "\10\71\1\370\4\71\1\74\52\71\1\0\3\3\1\0"+
    "\1\55\1\56\4\3\1\371\1\3\5\0\10\3\1\0"+
    "\13\3\1\0\1\3\11\0\2\3\1\0\3\3\2\0"+
    "\3\3\1\0\1\55\1\56\1\3\1\372\4\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\1\0\15\71\1\74\11\71\1\355\40\71\1\0"+
    "\3\3\1\0\1\55\1\56\1\3\1\373\4\3\5\0"+
    "\10\3\1\0\13\3\1\0\1\3\11\0\2\3\1\0"+
    "\3\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11032];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\1\11\6\1\1\11\10\1\12\11"+
    "\4\1\2\0\2\1\1\11\7\1\3\0\1\11\2\0"+
    "\1\11\1\0\23\1\1\11\1\1\1\0\11\1\4\0"+
    "\23\1\1\0\11\1\3\0\21\1\1\0\7\1\3\0"+
    "\20\1\1\0\5\1\3\0\14\1\1\0\4\1\1\11"+
    "\2\0\11\1\1\0\4\1\2\0\6\1\1\0\1\1"+
    "\2\0\3\1\1\0\1\1\2\0\1\11\2\1\1\0"+
    "\1\1\1\0\1\11\2\1\1\11\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[251];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
		


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico_Request(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexico_Request(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { return new Symbol(Simbolo.pyc, yycolumn,yyline,yytext());
          }
        case 59: break;
        case 32: 
          { return new Symbol(Simbolo.color, yycolumn,yyline,yytext());
          }
        case 60: break;
        case 29: 
          { return new Symbol(Simbolo.constante, yycolumn,yyline,yytext());
          }
        case 61: break;
        case 37: 
          { return new Symbol(Simbolo.avacio, yycolumn,yyline,yytext());
          }
        case 62: break;
        case 42: 
          { return new Symbol(Simbolo.CREACION, yycolumn,yyline,yytext());
          }
        case 63: break;
        case 4: 
          { return new Symbol(Simbolo.resta, yycolumn,yyline,yytext());
          }
        case 64: break;
        case 18: 
          { return new Symbol(Simbolo.NOT, yycolumn,yyline,yytext());
          }
        case 65: break;
        case 27: 
          { return new Symbol(Simbolo.get, yycolumn,yyline,yytext());
          }
        case 66: break;
        case 30: 
          { return new Symbol(Simbolo.mate, yycolumn,yyline,yytext());
          }
        case 67: break;
        case 58: 
          { return new Symbol(Simbolo.iniciousuario, yycolumn,yyline,yytext());
          }
        case 68: break;
        case 13: 
          { return new Symbol(Simbolo.corchetef, yycolumn,yyline,yytext());
          }
        case 69: break;
        case 48: 
          { return new Symbol(Simbolo.password, yycolumn,yyline,yytext());
          }
        case 70: break;
        case 17: 
          { return new Symbol(Simbolo.llavesf, yycolumn,yyline,yytext());
          }
        case 71: break;
        case 16: 
          { return new Symbol(Simbolo.llavesi, yycolumn,yyline,yytext());
          }
        case 72: break;
        case 36: 
          { return new Symbol(Simbolo.consulta ,yycolumn,yyline,yytext());
          }
        case 73: break;
        case 39: 
          { return new Symbol(Simbolo.nombre, yycolumn,yyline,yytext());
          }
        case 74: break;
        case 22: 
          { return new Symbol(Simbolo.OR, yycolumn,yyline,yytext());
          }
        case 75: break;
        case 25: 
          { return new Symbol(Simbolo.AND, yycolumn,yyline,yytext());
          }
        case 76: break;
        case 40: 
          { return new Symbol(Simbolo.tienda, yycolumn,yyline,yytext());
          }
        case 77: break;
        case 28: 
          { return new Symbol(Simbolo.potencia, yycolumn,yyline,yytext());
          }
        case 78: break;
        case 51: 
          { return new Symbol(Simbolo.telefono, yycolumn,yyline,yytext());
          }
        case 79: break;
        case 41: 
          { return new Symbol(Simbolo.tamano, yycolumn,yyline,yytext());
          }
        case 80: break;
        case 23: 
          { return new Symbol(Simbolo.de, yycolumn,yyline,yytext());
          }
        case 81: break;
        case 26: 
          { return new Symbol(Simbolo.imagen, yycolumn,yyline,yytext());
          }
        case 82: break;
        case 53: 
          { return new Symbol(Simbolo.ELIMINACION, yycolumn,yyline,yytext());
          }
        case 83: break;
        case 31: 
          { return new Symbol(Simbolo.tipo, yycolumn,yyline,yytext());
          }
        case 84: break;
        case 20: 
          { return new Symbol(Simbolo.id, yycolumn,yyline, yytext());
          }
        case 85: break;
        case 24: 
          { return new Symbol(Simbolo.raiz, yycolumn,yyline,yytext());
          }
        case 86: break;
        case 55: 
          { return new Symbol(Simbolo.MODIFICACION, yycolumn,yyline,yytext());
          }
        case 87: break;
        case 12: 
          { return new Symbol(Simbolo.corchetei,yycolumn,yyline,yytext());
          }
        case 88: break;
        case 47: 
          { return new Symbol(Simbolo.producto, yycolumn,yyline,yytext());
          }
        case 89: break;
        case 43: 
          { return new Symbol(Simbolo.request, yycolumn,yyline,yytext());
          }
        case 90: break;
        case 3: 
          { return new Symbol(Simbolo.numero, yycolumn,yyline,yytext());
          }
        case 91: break;
        case 56: 
          { return new Symbol(Simbolo.correo, yycolumn,yyline,yytext());
          }
        case 92: break;
        case 7: 
          { return new Symbol(Simbolo.DI, yycolumn,yyline,yytext());
          }
        case 93: break;
        case 19: 
          { return new Symbol(Simbolo.DF, yycolumn,yyline,yytext());
          }
        case 94: break;
        case 52: 
          { return new Symbol(Simbolo.direccion, yycolumn,yyline,yytext());
          }
        case 95: break;
        case 45: 
          { return new Symbol(Simbolo.extraer, yycolumn,yyline,yytext());
          }
        case 96: break;
        case 33: 
          { return new Symbol(Simbolo.marca, yycolumn,yyline,yytext());
          }
        case 97: break;
        case 11: 
          { return new Symbol(Simbolo.igual, yycolumn,yyline,yytext());
          }
        case 98: break;
        case 35: 
          { return new Symbol(Simbolo.donde, yycolumn,yyline,yytext());
          }
        case 99: break;
        case 8: 
          { return new Symbol(Simbolo.suma, yycolumn,yyline,yytext());
          }
        case 100: break;
        case 21: 
          { return new Symbol(Simbolo.cadena, yycolumn,yyline,yytext());
          }
        case 101: break;
        case 38: 
          { return new Symbol(Simbolo.codigo, yycolumn,yyline,yytext());
          }
        case 102: break;
        case 5: 
          { return new Symbol(Simbolo.division, yycolumn,yyline,yytext());
          }
        case 103: break;
        case 6: 
          { return new Symbol(Simbolo.multiplicacion, yycolumn,yyline,yytext());
          }
        case 104: break;
        case 15: 
          { return new Symbol(Simbolo.parentesisf, yycolumn,yyline,yytext());
          }
        case 105: break;
        case 14: 
          { return new Symbol(Simbolo.parentesisi, yycolumn,yyline,yytext());
          }
        case 106: break;
        case 2: 
          { return new Symbol(Simbolo.identificador, yycolumn,yyline,yytext());
          }
        case 107: break;
        case 10: 
          { return new Symbol(Simbolo.coma, yycolumn,yyline,yytext());
          }
        case 108: break;
        case 57: 
          { return new Symbol(Simbolo.crearusuario, yycolumn,yyline,yytext());
          }
        case 109: break;
        case 54: 
          { return new Symbol(Simbolo.propietario, yycolumn,yyline,yytext());
          }
        case 110: break;
        case 46: 
          { return new Symbol(Simbolo.cantidad, yycolumn,yyline,yytext());
          }
        case 111: break;
        case 44: 
          { return new Symbol(Simbolo.usuario, yycolumn,yyline,yytext());
          }
        case 112: break;
        case 50: 
          { return new Symbol(Simbolo.sucursal, yycolumn,yyline,yytext());
          }
        case 113: break;
        case 49: 
          { return new Symbol(Simbolo.apellido, yycolumn,yyline,yytext());
          }
        case 114: break;
        case 1: 
          { 
          }
        case 115: break;
        case 34: 
          { return new Symbol(Simbolo.email, yycolumn,yyline,yytext());
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Simbolo.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
