
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 15 20:03:37 CST 2016
//----------------------------------------------------

package BackEnd.Analizador.Compilador;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int raiz = 16;
  public static final int DI = 28;
  public static final int sucursal = 34;
  public static final int suma = 19;
  public static final int DF = 29;
  public static final int resta = 20;
  public static final int request = 31;
  public static final int MODIFICACION = 25;
  public static final int imagen = 46;
  public static final int ELIMINACION = 26;
  public static final int crearusuario = 37;
  public static final int correo = 11;
  public static final int coma = 48;
  public static final int tienda = 43;
  public static final int igual = 49;
  public static final int direccion = 42;
  public static final int identificador = 14;
  public static final int multiplicacion = 17;
  public static final int de = 22;
  public static final int NOT = 5;
  public static final int AND = 3;
  public static final int OR = 4;
  public static final int telefono = 40;
  public static final int numero = 13;
  public static final int parentesisi = 52;
  public static final int marca = 8;
  public static final int email = 41;
  public static final int parentesisf = 53;
  public static final int propietario = 45;
  public static final int EOF = 0;
  public static final int iniciousuario = 32;
  public static final int pyc = 2;
  public static final int producto = 6;
  public static final int nombre = 38;
  public static final int error = 1;
  public static final int color = 9;
  public static final int llavesi = 54;
  public static final int mate = 56;
  public static final int llavesf = 55;
  public static final int password = 35;
  public static final int potencia = 15;
  public static final int id = 33;
  public static final int avacio = 58;
  public static final int CREACION = 24;
  public static final int tipo = 47;
  public static final int corchetei = 50;
  public static final int donde = 23;
  public static final int tamano = 10;
  public static final int corchetef = 51;
  public static final int usuario = 36;
  public static final int apellido = 39;
  public static final int cantidad = 7;
  public static final int codigo = 44;
  public static final int extraer = 21;
  public static final int get = 30;
  public static final int constante = 27;
  public static final int division = 18;
  public static final int consulta = 57;
  public static final int cadena = 12;
}

