
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 12 22:26:47 CST 2016
//----------------------------------------------------

package BackEnd.Analizador.Compilador;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int raiz = 24;
  public static final int DI = 3;
  public static final int sucursal = 9;
  public static final int suma = 27;
  public static final int DF = 4;
  public static final int resta = 28;
  public static final int request = 6;
  public static final int MODIFICACION = 57;
  public static final int ELIMINACION = 58;
  public static final int imagen = 21;
  public static final int crearusuario = 12;
  public static final int correo = 34;
  public static final int coma = 39;
  public static final int tienda = 18;
  public static final int igual = 40;
  public static final int identificador = 37;
  public static final int direccion = 17;
  public static final int multiplicacion = 25;
  public static final int de = 54;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int OR = 51;
  public static final int telefono = 15;
  public static final int numero = 36;
  public static final int parentesisi = 43;
  public static final int marca = 31;
  public static final int email = 16;
  public static final int parentesisf = 44;
  public static final int propietario = 20;
  public static final int EOF = 0;
  public static final int iniciousuario = 7;
  public static final int pyc = 38;
  public static final int producto = 29;
  public static final int nombre = 13;
  public static final int error = 1;
  public static final int color = 32;
  public static final int llavesi = 45;
  public static final int mate = 47;
  public static final int llavesf = 46;
  public static final int password = 10;
  public static final int potencia = 23;
  public static final int id = 8;
  public static final int avacio = 49;
  public static final int CREACION = 56;
  public static final int tipo = 22;
  public static final int corchetei = 41;
  public static final int donde = 55;
  public static final int tamano = 33;
  public static final int corchetef = 42;
  public static final int usuario = 11;
  public static final int cantidad = 30;
  public static final int apellido = 14;
  public static final int codigo = 19;
  public static final int extraer = 53;
  public static final int get = 5;
  public static final int constante = 2;
  public static final int division = 26;
  public static final int consulta = 48;
  public static final int cadena = 35;
}

